Report1
Luda-Seliv-KE-413/PO_Seliv pull request #1
Opened 2023-10-28 08:08 UTC by Luda-Seliv-KE-413

Работа была слита (удалила репозиторий для разрешения конфликтов с ветвями в нём)

2023-10-28 08:14 UTC, lamer0k requested changes

2023-10-28 08:14 UTC, lamer0k commented on Report1.adoc
> +При запуске программы на контроллер подается питание. После чего контроллер переходит по адресу _0x800’0000_, срабатывает счетчик команд. +
счетчик команд не может срабатывать, он просто увеличивается каждый раз после выполнения команды на 1 и мы переходим на следующий адрес.

2023-10-28 08:14 UTC, lamer0k commented on Report1.adoc
> +Происходит переход в _таблицу векторов прерывания_, которая представляет из себя массив адресов. +
Самое ничего никогда не проихсодит :) Мы и так уже в таблице векторов прерываний, она наичнается по адресу 0x800 0000, просто первая запись там - это команда инициализации стека, потом переходим на следующий адрес, а там адрес функции инициализации.

2023-11-03 13:59 UTC, Luda-Seliv-KE-413 commented on Report1.adoc
> +При запуске программы на контроллер подается питание. После чего контроллер переходит по адресу _0x800’0000_, срабатывает счетчик команд. +
Правки внесены

2023-11-03 13:59 UTC, Luda-Seliv-KE-413 commented on Report1.adoc
> +Происходит переход в _таблицу векторов прерывания_, которая представляет из себя массив адресов. +
Правки внесены

2023-11-04 08:30 UTC, lamer0k approved these changes

2023-11-04 08:32 UTC, merged