Report2
Luda-Seliv-KE-413/PO_Seliv pull request #2
Opened 2023-10-28 08:09 UTC by Luda-Seliv-KE-413

Работа была слита

2023-10-28 08:15 UTC, lamer0k requested changes

2023-10-28 08:15 UTC, lamer0k commented on Report2.adoc
> +---
В отдельную папку надо убрать весь отчет, чтобы не было свалки в главной ветке.

2023-11-03 14:30 UTC, Luda-Seliv-KE-413 commented on Report2.adoc
> +---
Правки внесены

2023-11-04 08:30 UTC, lamer0k approved these changes

2023-11-04 08:33 UTC, merged