Report3
Luda-Seliv-KE-413/PO_Seliv pull request #3
Opened 2023-10-28 08:11 UTC by Luda-Seliv-KE-413

Были внесены правки, но не слита

2023-10-28 08:18 UTC, lamer0k requested changes

2023-10-28 08:18 UTC, lamer0k commented on Report3.adoc
> +:icons: font
В отдельную папку тоже надо кинуть.

2023-10-28 08:18 UTC, lamer0k commented on Report3.adoc
> + Для того чтобы одна переменная хранила адрес (взяла адрес) другой переменной используют оператор _&_ +
Можно попонятнее написать, для того, чтобы узнать адрес переменной, используется оператор взятия адреса.

2023-10-28 08:18 UTC, lamer0k commented on Report3.adoc
> + *Разименовывание* - обратная операция операции взятия адреса, которая выводит значение, хранимое по адресу указанному в указателе.
Разыменовывание.

2023-11-03 14:36 UTC, Luda-Seliv-KE-413 commented on Report3.adoc
> +:icons: font
Правки внесены

2023-11-03 14:36 UTC, Luda-Seliv-KE-413 commented on Report3.adoc
> + Для того чтобы одна переменная хранила адрес (взяла адрес) другой переменной используют оператор _&_ +
Правки внесены

2023-11-03 14:36 UTC, Luda-Seliv-KE-413 commented on Report3.adoc
> + *Разименовывание* - обратная операция операции взятия адреса, которая выводит значение, хранимое по адресу указанному в указателе.
Правки внесены

2023-11-04 08:29 UTC, lamer0k approved these changes

2023-11-04 08:34 UTC, merged