Laba1
Luda-Seliv-KE-413/PO_Seliv pull request #4
Opened 2023-10-28 08:13 UTC by Luda-Seliv-KE-413

2023-10-28 08:19 UTC, lamer0k requested changes

2023-10-28 08:19 UTC, lamer0k commented on Laba1.adoc
> +:icons: font
в отдельную папку надо скинуть.

2023-11-03 14:50 UTC, Luda-Seliv-KE-413 commented on Laba1.adoc
> +:icons: font
Правки внесены

2023-11-04 08:30 UTC, lamer0k approved these changes

2023-11-04 08:35 UTC, merged