Laba2
Luda-Seliv-KE-413/PO_Seliv pull request #5
Opened 2023-10-28 08:15 UTC by Luda-Seliv-KE-413

2023-10-28 08:20 UTC, lamer0k requested changes

2023-10-28 08:20 UTC, lamer0k commented on Laba2.adoc
> +:toc: macro
В отдельную папку Laba2 надо все скинуть

2023-11-03 14:55 UTC, Luda-Seliv-KE-413 commented on Laba2.adoc
> +:toc: macro
Правки внесены

2023-11-04 08:29 UTC, lamer0k approved these changes

2023-11-04 08:36 UTC, merged