Laba3
Luda-Seliv-KE-413/PO_Seliv pull request #6
Opened 2023-11-04 08:40 UTC by Luda-Seliv-KE-413

2023-11-18 11:50 UTC, lamer0k requested changes

2023-11-18 11:50 UTC, lamer0k commented on Laba3.adoc/Laba3.adoc
> +Регистр имеет поля различной длины:
Тут то не про размер поля регистра идет речь, а про возможные значения коэффициентов ФАПЧ.

2023-11-18 11:50 UTC, lamer0k commented on Laba3.adoc/Laba3.adoc
> +Ответ: Унарный плюс – это один из операторов программирования, который используется *для преобразования строки или переменной в числовое значение*.
Не верно,  Он не преобразует строку в число. А что он делает?

2023-11-18 12:48 UTC, Luda-Seliv-KE-413 commented on Laba3.adoc/Laba3.adoc
> +Ответ: Унарный плюс – это один из операторов программирования, который используется *для преобразования строки или переменной в числовое значение*.
Правки внесены

2023-11-18 12:48 UTC, Luda-Seliv-KE-413 commented on Laba3.adoc/Laba3.adoc
> +Регистр имеет поля различной длины:
Правки внесены

2023-12-16 09:16 UTC, lamer0k approved these changes

2023-12-16 11:08 UTC, merged